### ISSUE TITLE
poudriere image: Allow specifying a custom package repository

### ISSUE THREAD

**Issue by Savagedlight** [Savagedlight/poudriere#4]
Use case: building images on a different system than the package builder.

Currently, poudriere image assumes there is a locally built package repository, and fails if it doesn't exist.

Solution: Allow specifying custom package repository using a command line option or environment variable.

**Comment by Savagedlight** [comment]
Approach: Add command line option -P, and require that the custom repository is configured already. Either through alterations to the poudriere jail, or using the file overlay feature (-c).

**Comment by allanjude** [comment]
It seems the 'pkgreponame' used by this -P flag is never actually used.

I wonder if it would make more sense to change this to be the path to a repo config file, that it would copy into the image and run from there. This also avoids needing the repo to be configured on the image building machine (but doesn't conflict with that)

**Comment by allanjude** [comment]
I've extracted this commit into its own branch (and finally, years late, opened the PR for the rest of zfs send upstream)

https://github.com/allanjude/poudriere/tree/image_pkg_repo
